import pandas as pd
import numpy as np
import traceback
from datetime import datetime

def safe_execute_code(df: pd.DataFrame, code: str) -> dict:
    """Safely execute pandas code generated by the AI agent."""
    local_vars = {"df": df.copy(), "pd": pd, "np": np}
    result = {"data": None, "error": None, "type": "unknown"}
    try:
        exec(compile(code, "<string>", "exec"), {"__builtins__": {}}, local_vars)
        output = local_vars.get("result", None)
        if output is None:
            for var in ["output", "answer", "res"]:
                if var in local_vars:
                    output = local_vars[var]
                    break
        if isinstance(output, pd.DataFrame):
            result["data"] = output.fillna("").to_dict(orient="records")
            result["columns"] = list(output.columns)
            result["type"] = "dataframe"
        elif isinstance(output, pd.Series):
            result["data"] = output.to_dict()
            result["type"] = "series"
        elif isinstance(output, (int, float, str, bool)):
            result["data"] = output
            result["type"] = "scalar"
        else:
            result["data"] = str(output)
            result["type"] = "text"
    except Exception as e:
        result["error"] = str(e)
        result["traceback"] = traceback.format_exc()
    return result

def generate_markdown_report(df: pd.DataFrame, question: str) -> str:
    """Generate a Markdown analytics report using OSS Python (no paid APIs)."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    lines = [
        f"# Auto-BI Assistant Report",
        f"**Generated:** {now}",
        f"**Question:** {question}",
        "",
        "## Dataset Overview",
        f"- **Rows:** {len(df)}",
        f"- **Columns:** {len(df.columns)}",
        f"- **Numeric columns:** {', '.join(numeric_cols) or 'None'}",
        "",
        "## Column Summary",
    ]
    for col in df.columns:
        dtype = str(df[col].dtype)
        nulls = int(df[col].isnull().sum())
        lines.append(f"- **{col}** ({dtype}): {nulls} missing values")

    if len(numeric_cols) > 0:
        lines.append("")
        lines.append("## Descriptive Statistics")
        lines.append("")
        lines.append(df[numeric_cols].describe().round(4).to_markdown())

    lines.append("")
    lines.append("## Sample Data (first 5 rows)")
    lines.append("")
    lines.append(df.head(5).fillna("").to_markdown(index=False))
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [Auto-BI Assistant](https://github.com/amalsp220/auto-bi-assistant)*")
    return "\n".join(lines)
